config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do

  mount API => "/"

  root 'home#index'
  get 'home/api_swagger_ui'

  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end


  # 用户相关
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  # 第三方登录
  match "/auth/:provider/callback", :to => 'omniauths#create', via: [:get, :post]

  resources :users do
    collection do
      get 'verify_email'
    end
    member do
      get :following, :followers
    end
  end
  resource :settings do
    collection do
      get :account
    end
  end
  resources :relationships, only: [:create, :destroy]

  scope module: :member do
    resources :collects, only: [:create, :destroy]
    resources :tags, only: [:index]
  end


  # 商品相关
  resources :products do
    resources :comments, only: [:create, :destroy]
  end

  # 抓取内容news
  resources :posts do
    collection do
      get :search
    end
  end


  # 七牛上传文件
  namespace :upload do
    resources :qiniu, only: [] do
      collection do
        get 'image_up_token'
      end
    end
  end


  # 管理员
  draw :admin

end

app/views/shared/_function_tips.html.erb
<div class="tips col-sm-0 col-md-2 col-md-offset-1">
	<% case type %>
	<% when "collect" %>
		<div id="collect_<%= product.id %>" class="trip-collect">
			<% if current_user && current_user.collecting?(product, "product") %>
	      <%= render partial: 'member/collects/cancel_collect', locals: {product: product} %>
	    <% else %>
	      <%= render partial: 'member/collects/collect', locals: {product: product} %>
	    <% end %>
	  </div>
		<div class="line"></div>
		<div class="tips_content" id="collect_count"><%= product.user_collect_products_count %> 人收藏了此文章</div>
	
	<% when "info" %>
		<div class="tips_content">文章信息</div>
		<%= user_avatar(product.user.avatar_path, '40x40') %>
		<%= link_to product.user.name, product.user %>
		发布于
		<%= time_ago_in_words product.created_at %>
	
	<% when "category" %>
		<div class="tips_content">所属标签</div>
		<%= product.categories.map(&:name) %>
	
	<% when "watch" %>
		<p><%= link_to "返回文章列表", posts_path, class: "btn btn-info btn-block" %></p>
		<div class="tips_content"><%= watch_count %> 人查看了此文章</div>
	<% end %>
</div>

app/views/shared/_setting_nav.html.erb
<ol class="breadcrumb">
	<%= nav_link '个人信息', edit_user_path(current_user), 'active' %>
	<%= nav_link '账户信息', account_settings_path, 'active' %>
	<%= nav_link '密码重置', "#", 'active' %>
	<%= nav_link '通知设置', "#", 'active' %>
</ol>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		关注
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="follower" class="stat">
			<%= @user.followers.count %>
		</strong>
		关注者
	</a>
</div>