config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do

  mount API => "/"

  root 'home#index'
  get 'home/api_swagger_ui'

  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end


  # 用户相关
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  # 第三方登录
  match "/auth/:provider/callback", :to => 'omniauths#create', via: [:get, :post]

  resources :users do
    collection do
      get 'verify_email'
    end
    member do
      get :following, :followers
    end
  end
  resource :settings do
    collection do
      get :account
    end
  end
  resources :relationships, only: [:create, :destroy]

  scope module: :member do
    resources :collects, only: [:create, :destroy]
    resources :tags, only: [:index]
  end


  # 商品相关
  resources :products do
    resources :comments, only: [:create, :destroy]
  end

  # 抓取内容news
  resources :posts do
    collection do
      get :search
    end
  end


  # 七牛上传文件
  namespace :upload do
    resources :qiniu, only: [] do
      collection do
        get 'image_up_token'
      end
    end
  end


  # 管理员
  draw :admin

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	unless signed_in?
  		render 'cover_home', layout: false
  	end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/cover_home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<style type="text/css">
		body {
			display: table;
	    position: relative;
	    width: 100%;
	    height: 100%;
			background: url(<%= asset_path "bg#{rand(1..2)}.jpg" %>) no-repeat center center fixed; 
			-webkit-background-size: cover; 
			-moz-background-size: cover; 
			-o-background-size: cover;
			background-size: cover; 
		}
		.cover-login {
			background-color: white;
			width: 40%;
			margin-left: auto;
			margin-right: auto;
			text-align: center;
			line-height: 50px;
			border: 5px solid #dedede;
    	-moz-border-radius: 15px;      /* Gecko browsers */
    	-webkit-border-radius: 15px;   /* Webkit browsers */
    	border-radius:15px;            /* W3C syntax */
		}
		ul {
			list-style: none;
		}
		ul li {
			font-size: 25px;
			font-weight: bold;
			/*font-style: italic;*/
		}
		ul li a {
			text-decoration: none;
			color: black;
		}
		ul li a:hover {
			text-decoration: underline;
		}
		</style>
	</head>

		<body>
			<div class="cover-login">
				<ul class="login-way">
					<li><%= link_to "登录", login_path %></li>
	    		<li><%= link_to "注册", new_user_path %></li>
	    		<li><%= link_to "微博登录", "/auth/weibo" %></li>
	    		<li><%= link_to "qq登录", "/auth/qq_connect" %></li>
	    		<li><%= link_to "豆瓣登录", "/auth/douban" %></li>
	    		<li><%= link_to "github登录", "/auth/github" %></li>
	    		<li><%= link_to "随便看看", posts_path %></li>
    		</ul>
			</div>
		</body>
</html>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Hello word!</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" href="/home/api_swagger_ui" role="button">API文档</a></p>
</div>