config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do

  mount API => "/"

  root 'home#index'
  get 'home/api_swagger_ui'

  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end


  # 用户相关
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  # 第三方登录
  match "/auth/:provider/callback", :to => 'omniauths#create', via: [:get, :post]

  resources :users do
    collection do
      get 'verify_email'
    end
    member do
      get :following, :followers
    end
  end
  resource :settings do
    collection do
      get :account
    end
  end
  resources :relationships, only: [:create, :destroy]

  scope module: :member do
    resources :collects, only: [:create, :destroy]
    resources :tags, only: [:index]
  end


  # 商品相关
  resources :products do
    resources :comments, only: [:create, :destroy]
  end

  # 抓取内容news
  resources :posts do
    collection do
      get :search
    end
  end


  # 七牛上传文件
  namespace :upload do
    resources :qiniu, only: [] do
      collection do
        get 'image_up_token'
      end
    end
  end


  # 管理员
  draw :admin

end

app/models/product.rb
class Product < ActiveRecord::Base
	# include Obfuscate

	# 发布人
	belongs_to :user
	# 收藏
	has_many :user_collect_products, dependent: :destroy
	has_many :collected_user, through: :user_collect_products, source: :user
	# 分类
	has_many :product_category_ships, dependent: :destroy
	has_many :categories, through: :product_category_ships
	# 评论
	has_many :comments, as: :commentable

	# 验证
	validates_presence_of :user, :cover_path
	validates :title, presence: true, length: { maximum: 30 }
	validates :describe, presence: true, length: { maximum: 5000 }
	
	# 排序
	scope :category_for, ->(category_name) { joins(:categories).where("categories.name = ?", category_name)}

	def cover_path_with_size(width, height)
		"#{self.cover_path}?imageView2/1/w/#{width}/h/#{height}"
	end

	# def to_param
 #    encrypt id
 #  end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :signed_in_user, only: [ :new, :create ]

	def index
		@products = Product.order(id: :desc)
		@products = @products.category_for(params[:category]) if params[:category]
		@products = @products.paginate(page: params[:page], per_page: 12)
		@categories = Category.all
	end

	def show
		@product = Product.find(params[:id])
		# @product = Product.find Product.decrypt(params[:id])
		@comments = @product.comments
		@comment = Comment.new
	end

	def new
		@product = current_user.products.build
	end

	def create
		@product = current_user.products.build(product_params)

		if @product.save
			flash[:success] = "发布成功"
      redirect_to product_path(@product)
		else
			flash.now[:danger] = "发布失败"
			render 'new'
		end
	end

	private

		def product_params
			params.require(:product).permit(:title, :describe, :cover_path, category_ids: [])
		end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="content-side">
  <p class="section-name">选择分类</p>
  <ul class="section-value">
    <% @categories.each do |category| %>
      <%= nav_link category.name, products_path(category: category.name), "", true %>
    <% end %>
  </ul>
</div>

<div class="content-main">
  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4">
    <article class="trip-g">
      <%= link_to image_tag(product.cover_path_with_size("330", "200")), product, class: "cover" %>
      <div class="trip-c">
        <h1><%= product.title %></h1>
        <div class="trip-desc"><%= truncate(strip_tags(product.describe), length: 30) %></div>
      </div>

      <div class="trip-collect glyphicon glyphicon-star"><%= product.user_collect_products_count %></div>
    </article>
    </div>
  <% end %>
</div>

<%= will_paginate @products, renderer: BootstrapPagination::Rails %>

app/views/products/new.html.erb
<% provide(:title, '创建商品') %>
<%#= stylesheet_link_tag 'doc/simditor/editor' %>
<%#= stylesheet_link_tag 'doc/simditor/fonticon' %>
<%= stylesheet_link_tag 'doc/simditor/simditor' %>
<%= stylesheet_link_tag 'doc/simditor/simditor-mention.css' %>

<%= simple_form_for @product, html: { class: "form-horizontal"} do |f| %>
  <div class="col-sm-8 col-sm-offset-2">
    <%= f.input :title, input_html: { maxlength: 30 }, autofocus: true %>

    <%= f.input :describe, as: :text, input_html: { id: 'editor', maxlength: 5000 } %>

    <%= f.input :cover_path, input_html: { id: "cover_path", readonly: true } %>
    <a class="btn btn-default btn-lg" id="pickfiles">增加图片</a>
    <br/>
    <img src="<%= @product.cover_path %>" id="show_cover_path" width="100" height="100"/>

    <%= f.association :categories, as: :check_boxes %>

    </br></br></br>
    <%= f.button :submit, "发布创意", class: 'btn-lg btn-block', data: { disable_with: '发布中...' } %>
  </div>
<% end %>

<!-- qiniu -->
<%= javascript_include_tag 'upload/image_upload' %>
<!-- simditor -->
<%= javascript_include_tag 'doc/simditor/module.min.js' %>
<%= javascript_include_tag 'doc/simditor/hotkeys.min.js' %>
<%= javascript_include_tag 'doc/simditor/uploader.min.js' %>
<%= javascript_include_tag 'doc/simditor/simditor.min.js' %>
<!-- simditor扩展 -->
<%= javascript_include_tag 'doc/simditor/mark.js' %>
<%= javascript_include_tag 'doc/simditor/autosave.js' %>
<%= javascript_include_tag 'doc/simditor/simditor-dropzone.js' %>
<%= javascript_include_tag 'doc/simditor/simditor-mention.js' %>


<script>
    $(function () {

      // 编辑器
      // 获取上传token(可能出现token过期)
      $.getJSON("/upload/qiniu/image_up_token", function(data) {
        var uptoken = data.uptoken;
        // 初始化编辑器
        var editor = new Simditor({
          textarea: $('#editor'),
          placeholder: '详细描述下自己的创意吧',
          imageButton: ['upload', 'external'],
          upload: {
            url: 'http://up.qiniu.com/',
            fileKey: 'file',
            params: {
              token: uptoken
            },
            connectionCount: 3,
            leaveConfirm: '正在上传文件，如果离开上传会自动取消'
          },
          toolbar: ['title', 'bold', 'italic', 'underline', 'strikethrough', 'color', '|', 'ol', 'ul', 'blockquote', 'code', 'table', 'link', 'image', 'hr', 'indent', 'outdent', 'source', 'mark'],
          // toolbar: [
          //   'title'          # 标题文字
          //   'bold'           # 加粗文字
          //   'italic'         # 斜体文字
          //   'underline'      # 下划线文字
          //   'strikethrough'  # 删除线文字
          //   'color'          # 修改文字颜色
          //   'ol'             # 有序列表
          //   'ul'             # 无序列表
          //   'blockquote'     # 引用
          //   'code'           # 代码
          //   'table'          # 表格
          //   'link'           # 插入链接
          //   'image'          # 插入图片
          //   'hr'             # 分割线
          //   'indent'         # 向右缩进
          //   'outdent'        # 向左缩进
          //   'source'         # HTML源代码
          // ],
          pasteImage: true,
          autosave: 'editor-content',
          // @参数
          mention:{
            items:[
            {
              id:1,
              name:"Rails4 Start",
              pinyin:"chuangkejiazu",
              abbr:"ck",
              url:"http://www.example.com"
            }
            ], //item数组
            // url:"", //获取item数组的url,与items选项二选一
            // nameKey:"", //(可选,默认为name),item中用来提供名称的键
            // pinyinKey:"", //(可选,默认为pinyin),item中用来提供拼音的键
            // abbrKey:"", //(可选,默认为abbr),item中用来提供缩写的键
            //名称,拼音以及缩写将会用来匹配
            // itemRenderer:null, //(可选),对弹出框的item进行自定义,例如添加img元素
            // linkRender:null //(可选),对生成的a链接进行自定义
          }
        });
        // 上传成功后
        editor.uploader.on('uploadsuccess', function(e, file, result) {
          console.log($(this))
          console.log(result)
        });
      });
      // 封面图
      imageUpload.coverUploader('pickfiles', $('#show_cover_path'), $('#cover_path'));

    });
</script>

app/views/products/show.html.erb
<% provide(:title, '创意详情') %>

<%= link_to "返回列表", products_path, class: "btn btn-info" %>

<div class="post-entry col-md-12">
	<div class="post-title">
		<%= @product.title %>
	</div>

	<div class="row">
		<article class="col-sm-12 col-md-7 col-md-offset-1 post-content">
			<%= image_tag @product.cover_path_with_size("640", "300") %>
			<%= sanitize @product.describe %>
		</article>
		<%= render partial: 'shared/function_tips', locals: {type: "collect", product: @product} %>
		<%= render partial: 'shared/function_tips', locals: {type: "info", product: @product} %>
		<%= render partial: 'shared/function_tips', locals: {type: "category", product: @product} %>
	</div>
</div>

<div class="comment-body" data-users="<%= @comments.map {|c| c.user.name}.uniq %>">
	<% if @comments.any? %>
		<% @comments.each do |comment| %>
				<%= comment.user.name %>
				<%= emojify(sanitize(comment.content_html)) %>
			</br>
		<% end %>
	<% end %>
</div>

<%= simple_form_for [@product, @comment] do |f| %>
	
	<%= f.input :content, as: :text %>
	<%= f.button :submit, "保存" %>

<% end %>

<script>
	$(function(){
    data = $(".comment-body").data("users");
    $('textarea').atwho({at:"@", 'data':data});
	});
</script>